public class ExceptionHandle {
    public static void main(String[] args) {
//        try {
//            int a = 10;
//            int b = 9;
//            System.out.println(a / b);
//        } catch (ArithmeticException exception) {
//            System.out.println("Lỗi chia cho 0 kìa");
//        } catch (NullPointerException e) {
//            System.out.println(e.getMessage());
//        } catch (IndexOutOfBoundsException exception) {
//            System.out.println(exception.getMessage());
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
//        System.out.println("Hello C06");
//        try {
//            int a = 10;
//            int b = 0;
//            System.out.println(a / b);
//            System.out.println("Hello");
//        } finally { // Dù dúng hay sai thì cũng chạy
//            System.out.println("Finally");
//        }
//        System.out.println("End");
    }



}
